CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE asp_net_roles (
    id text NOT NULL,
    system_id uuid,
    is_enabled boolean NOT NULL,
    user_update text,
    user_create text,
    date_update timestamp with time zone,
    date_create timestamp with time zone,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE asp_net_users (
    id text NOT NULL,
    full_name text,
    management_code text,
    secret_question text,
    secret_answer text,
    is_enabled boolean NOT NULL,
    entity_type text,
    document_type text,
    document_number text,
    source_system text,
    last_login_provider text,
    last_login_date timestamp with time zone,
    user_update text,
    user_create text,
    date_update timestamp with time zone,
    date_create timestamp with time zone,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE provider_configurations (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    provider_name character varying(50) NOT NULL,
    provider_type character varying(30),
    client_id character varying(200),
    client_secret character varying(200),
    endpoint_url character varying(200),
    scopes character varying(200),
    enabled boolean NOT NULL,
    last_modified timestamp with time zone NOT NULL,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_provider_configurations PRIMARY KEY (id)
);

CREATE TABLE system_registries (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    system_code character varying(50) NOT NULL,
    system_name character varying(100) NOT NULL,
    description text,
    base_url character varying(200) NOT NULL,
    icon_url character varying(200),
    is_enabled boolean NOT NULL,
    category character varying(50),
    contact_email character varying(100),
    is_central_admin boolean NOT NULL,
    last_sync timestamp with time zone,
    api_key text,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_system_registries PRIMARY KEY (id)
);

CREATE TABLE asp_net_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_tokens (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE auth_audit_logs (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text,
    provider_name character varying(50),
    event_type character varying(50),
    ip_address character varying(50),
    user_agent text,
    event_date timestamp with time zone NOT NULL,
    details jsonb,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_auth_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_auth_audit_logs_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id)
);

CREATE TABLE email_verification_tokens (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text NOT NULL,
    email character varying(256) NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL DEFAULT FALSE,
    used_at timestamp with time zone,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_email_verification_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE mfa_backup_codes (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text NOT NULL,
    code character varying(20) NOT NULL,
    is_used boolean NOT NULL DEFAULT FALSE,
    used_at timestamp with time zone,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_mfa_backup_codes PRIMARY KEY (id),
    CONSTRAINT fk_mfa_backup_codes_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_revoked boolean NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by_token text,
    device_info text,
    ip_address text,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE user_authentication_providers (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text,
    provider_type character varying(30) NOT NULL,
    provider_name character varying(50),
    external_user_id character varying(200),
    last_sync timestamp with time zone,
    is_active boolean NOT NULL,
    application_user_id text,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_user_authentication_providers PRIMARY KEY (id),
    CONSTRAINT "fk_user_authentication_providers_asp_net_users_application_use~" FOREIGN KEY (application_user_id) REFERENCES asp_net_users (id),
    CONSTRAINT fk_user_authentication_providers_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id)
);

CREATE TABLE user_password_histories (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id character varying(450) NOT NULL,
    password_hash text NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_user_password_histories PRIMARY KEY (id),
    CONSTRAINT fk_user_password_histories_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE user_sessions (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id text NOT NULL,
    jwt_id character varying(100) NOT NULL,
    token_type text NOT NULL,
    system_name character varying(100) NOT NULL,
    device character varying(500) NOT NULL,
    ip_address character varying(45),
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_revoked boolean NOT NULL DEFAULT FALSE,
    revoked_at timestamp with time zone,
    audience character varying(100),
    scope character varying(100),
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id),
    CONSTRAINT fk_user_sessions_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id)
);

CREATE TABLE menus (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    parent_id uuid,
    system_id uuid NOT NULL,
    menu_label character varying(50) NOT NULL,
    description character varying(150),
    level smallint NOT NULL,
    module character varying(50),
    module_type character varying(25),
    required_claim_type text,
    required_claim_min_value integer NOT NULL,
    icon_url character varying(200),
    access_scope character varying(15),
    order_index smallint NOT NULL,
    bit_position integer,
    url text,
    user_create text,
    date_create timestamp with time zone,
    user_update text,
    date_update timestamp with time zone,
    CONSTRAINT pk_menus PRIMARY KEY (id),
    CONSTRAINT fk_menus_menus_parent_id FOREIGN KEY (parent_id) REFERENCES menus (id) ON DELETE CASCADE,
    CONSTRAINT fk_menus_system_registries_system_id FOREIGN KEY (system_id) REFERENCES system_registries (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);

CREATE UNIQUE INDEX role_name_index ON asp_net_roles (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);

CREATE INDEX email_index ON asp_net_users (normalized_email);

CREATE UNIQUE INDEX user_name_index ON asp_net_users (normalized_user_name);

CREATE INDEX ix_auth_audit_logs_user_id ON auth_audit_logs (user_id);

CREATE INDEX ix_email_verification_tokens_user_id ON email_verification_tokens (user_id);

CREATE INDEX ix_menus_parent_id ON menus (parent_id);

CREATE INDEX ix_menus_system_id ON menus (system_id);

CREATE UNIQUE INDEX uix_mfa_backup_codes_user_code ON mfa_backup_codes (user_id, code);

CREATE UNIQUE INDEX ix_provider_configurations_provider_name ON provider_configurations (provider_name);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE UNIQUE INDEX ix_system_registries_system_code ON system_registries (system_code);

CREATE INDEX ix_user_authentication_providers_application_user_id ON user_authentication_providers (application_user_id);

CREATE UNIQUE INDEX ix_user_authentication_providers_user_id_provider_name ON user_authentication_providers (user_id, provider_name);

CREATE UNIQUE INDEX uq_user_password ON user_password_histories (user_id, password_hash);

CREATE UNIQUE INDEX ix_user_sessions_user_id_jwt_id ON user_sessions (user_id, jwt_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251210141919_InitialSsoSetup', '8.0.22');

COMMIT;

